#-----------------------------------------------------------------------------------------------------------------------------------------------

### USER REGISTER 
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "nosenose5",
    "email": "nosenose5@gmail.com",
    "password": "nosenose5"
}

### LOGIN USER
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "nosenose5@gmail.com",
    "password": "nosenose5"
}

### LOGOUT USER
POST http://localhost:3000/api/auth/logout

#-----------------------------------------------------------------------------------------------------------------------------------------------

### PETICIONES DE TODOS LOS PRODUCTOS
GET http://localhost:3000/api/products

#-----------------------------------------------------------------------------------------------------------------------------------------------

### CREAR PRODUCTO
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "producto a eliminar",
    "description": "eliminarrrrrrrrrrrrrrrrrrrrrrr",
    "price": 11111,
    "stock": 5,
    "imageUrl": "https://res.cloudinary.com/dzxa0ykpd/image/upload/v1780970041/D_716149-MLA82553365374_032025-C_wqdwiv.jpg"
}


### ACTUALIZAR PRODUCTO
PUT http://localhost:3000/api/products/6a281fae290edf788c0e772a
Content-Type: application/json

{
    "price": 8500
}


### OBTENER UN PRODUCTO
GET http://localhost:3000/api/products/6a281fae290edf788c0e772a


### ELIMINAR UN PRODUCTO
DELETE http://localhost:3000/api/products/6a28417b4895e722fb433574


#-----------------------------------------------------------------------------------------------------------------------------------------------

### ADD TO CART
POST http://localhost:3000/api/cart/add
Content-Type: application/json

{
    "userId": "6a1eff5638fab48282df7bee",
    "productId": "6a281fae290edf788c0e772a",
    "quantity": 1
}

### GET CART
GET http://localhost:3000/api/cart/get/6a1eff5638fab48282df7bee

### UPTADE CART
PUT http://localhost:3000/api/cart/update/6a1eff5638fab48282df7bee
Content-Type: application/json

{
    "userId": "6a1eff5638fab48282df7bee",
    "productId": "6a281fae290edf788c0e772a",
    "quantity": 10
}

### DELETE CART
DELETE http://localhost:3000/api/cart/delete/6a1eff5638fab48282df7bee

#-----------------------------------------------------------------------------------------------------------------------------------------------

